// 自动生成: 全球语言目录 (与后端 backend/src/data/languages.js 同步)。勿手改。
export const LANGUAGES = [
  { code: 'aa', name: 'Afar', native: 'Afaraf', cn: '阿法尔语', deepL: 0 },
  { code: 'ab', name: 'Abkhazian', native: 'аҧсуа бызшәа', cn: '阿布哈兹语', deepL: 0 },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans', cn: '南非荷兰语', deepL: 0 },
  { code: 'ak', name: 'Akan', native: 'Akan', cn: '阿坎语', deepL: 0 },
  { code: 'am', name: 'Amharic', native: 'አማርኛ', cn: '阿姆哈拉语', deepL: 0 },
  { code: 'ar', name: 'Arabic', native: 'العربية', cn: '阿拉伯语', deepL: 1 },
  { code: 'an', name: 'Aragonese', native: 'aragonés', cn: '阿拉贡语', deepL: 0 },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া', cn: '阿萨姆语', deepL: 0 },
  { code: 'av', name: 'Avaric', native: 'авар мацӀ', cn: '阿瓦尔语', deepL: 0 },
  { code: 'ae', name: 'Avestan', native: 'avesta', cn: '阿维斯陀语', deepL: 0 },
  { code: 'ay', name: 'Aymara', native: 'aymar aru', cn: '艾马拉语', deepL: 0 },
  { code: 'az', name: 'Azerbaijani', native: 'azərbaycan dili', cn: '阿塞拜疆语', deepL: 0 },
  { code: 'ba', name: 'Bashkir', native: 'башҡорт теле', cn: '巴什基尔语', deepL: 0 },
  { code: 'bm', name: 'Bambara', native: 'bamanankan', cn: '班巴拉语', deepL: 0 },
  { code: 'be', name: 'Belarusian', native: 'беларуская мова', cn: '白俄罗斯语', deepL: 0 },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', cn: '孟加拉语', deepL: 0 },
  { code: 'bh', name: 'Bihari', native: 'भोजपुरी', cn: '比哈尔语', deepL: 0 },
  { code: 'bi', name: 'Bislama', native: 'Bislama', cn: '比斯拉马语', deepL: 0 },
  { code: 'bo', name: 'Tibetan', native: 'བོད་ཡིག', cn: '藏语', deepL: 0 },
  { code: 'bs', name: 'Bosnian', native: 'bosanski jezik', cn: '波斯尼亚语', deepL: 0 },
  { code: 'br', name: 'Breton', native: 'brezhoneg', cn: '布列塔尼语', deepL: 0 },
  { code: 'bg', name: 'Bulgarian', native: 'български език', cn: '保加利亚语', deepL: 1 },
  { code: 'ca', name: 'Catalan', native: 'català', cn: '加泰罗尼亚语', deepL: 0 },
  { code: 'cs', name: 'Czech', native: 'čeština', cn: '捷克语', deepL: 1 },
  { code: 'ch', name: 'Chamorro', native: 'Chamoru', cn: '查莫罗语', deepL: 0 },
  { code: 'ce', name: 'Chechen', native: 'нохчийн мотт', cn: '车臣语', deepL: 0 },
  { code: 'cu', name: 'Church Slavic', native: 'ѩзыкъ словѣньскъ', cn: '教会斯拉夫语', deepL: 0 },
  { code: 'cv', name: 'Chuvash', native: 'чӑваш чӗлхи', cn: '楚瓦什语', deepL: 0 },
  { code: 'kw', name: 'Cornish', native: 'Kernewek', cn: '康沃尔语', deepL: 0 },
  { code: 'co', name: 'Corsican', native: 'corsu', cn: '科西嘉语', deepL: 0 },
  { code: 'cr', name: 'Cree', native: 'ᓀᐦᐃᔭᐍᐏᐣ', cn: '克里语', deepL: 0 },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg', cn: '威尔士语', deepL: 0 },
  { code: 'da', name: 'Danish', native: 'dansk', cn: '丹麦语', deepL: 1 },
  { code: 'de', name: 'German', native: 'Deutsch', cn: '德语', deepL: 1 },
  { code: 'dv', name: 'Divehi', native: 'ދިވެހި', cn: '迪维希语', deepL: 0 },
  { code: 'dz', name: 'Dzongkha', native: 'རྫོང་ཁ', cn: '宗喀语', deepL: 0 },
  { code: 'el', name: 'Greek', native: 'Ελληνικά', cn: '希腊语', deepL: 1 },
  { code: 'en', name: 'English', native: 'English', cn: '英语', deepL: 1 },
  { code: 'eo', name: 'Esperanto', native: 'Esperanto', cn: '世界语', deepL: 0 },
  { code: 'et', name: 'Estonian', native: 'eesti', cn: '爱沙尼亚语', deepL: 1 },
  { code: 'eu', name: 'Basque', native: 'euskara', cn: '巴斯克语', deepL: 0 },
  { code: 'ee', name: 'Ewe', native: 'Eʋegbe', cn: '埃维语', deepL: 0 },
  { code: 'fo', name: 'Faroese', native: 'føroyskt', cn: '法罗语', deepL: 0 },
  { code: 'fa', name: 'Persian', native: 'فارسی', cn: '波斯语', deepL: 0 },
  { code: 'fj', name: 'Fijian', native: 'vosa Vakaviti', cn: '斐济语', deepL: 0 },
  { code: 'fi', name: 'Finnish', native: 'suomi', cn: '芬兰语', deepL: 1 },
  { code: 'fr', name: 'French', native: 'français', cn: '法语', deepL: 1 },
  { code: 'fy', name: 'Western Frisian', native: 'Frysk', cn: '西弗里西亚语', deepL: 0 },
  { code: 'ff', name: 'Fulah', native: 'Fulfulde', cn: '富拉语', deepL: 0 },
  { code: 'gd', name: 'Gaelic', native: 'Gàidhlig', cn: '苏格兰盖尔语', deepL: 0 },
  { code: 'ga', name: 'Irish', native: 'Gaeilge', cn: '爱尔兰语', deepL: 0 },
  { code: 'gl', name: 'Galician', native: 'galego', cn: '加利西亚语', deepL: 0 },
  { code: 'gv', name: 'Manx', native: 'Gaelg', cn: '马恩岛语', deepL: 0 },
  { code: 'gn', name: 'Guarani', native: 'Avañe\'ẽ', cn: '瓜拉尼语', deepL: 0 },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', cn: '古吉拉特语', deepL: 0 },
  { code: 'ht', name: 'Haitian', native: 'Kreyòl ayisyen', cn: '海地克里奥尔语', deepL: 0 },
  { code: 'ha', name: 'Hausa', native: 'Hausa', cn: '豪萨语', deepL: 0 },
  { code: 'he', name: 'Hebrew', native: 'עברית', cn: '希伯来语', deepL: 0 },
  { code: 'hz', name: 'Herero', native: 'Otjiherero', cn: '赫雷罗语', deepL: 0 },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', cn: '印地语', deepL: 1 },
  { code: 'ho', name: 'Hiri Motu', native: 'Hiri Motu', cn: '希里莫图语', deepL: 0 },
  { code: 'hr', name: 'Croatian', native: 'hrvatski jezik', cn: '克罗地亚语', deepL: 0 },
  { code: 'hu', name: 'Hungarian', native: 'magyar', cn: '匈牙利语', deepL: 1 },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն', cn: '亚美尼亚语', deepL: 0 },
  { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo', cn: '伊博语', deepL: 0 },
  { code: 'io', name: 'Ido', native: 'Ido', cn: '伊多语', deepL: 0 },
  { code: 'ii', name: 'Sichuan Yi', native: 'ꆈꌠꉙ', cn: '四川彝语', deepL: 0 },
  { code: 'iu', name: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ', cn: '因纽特语', deepL: 0 },
  { code: 'ie', name: 'Interlingue', native: 'Interlingue', cn: '西方国际语', deepL: 0 },
  { code: 'ia', name: 'Interlingua', native: 'Interlingua', cn: '国际语', deepL: 0 },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia', cn: '印尼语', deepL: 1 },
  { code: 'ik', name: 'Inupiaq', native: 'Iñupiaq', cn: '伊努皮克语', deepL: 0 },
  { code: 'is', name: 'Icelandic', native: 'Íslenska', cn: '冰岛语', deepL: 0 },
  { code: 'it', name: 'Italian', native: 'Italiano', cn: '意大利语', deepL: 1 },
  { code: 'jv', name: 'Javanese', native: 'basa Jawa', cn: '爪哇语', deepL: 0 },
  { code: 'ja', name: 'Japanese', native: '日本語', cn: '日语', deepL: 1 },
  { code: 'kl', name: 'Kalaallisut', native: 'kalaallisut', cn: '格陵兰语', deepL: 0 },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', cn: '卡纳达语', deepL: 0 },
  { code: 'ks', name: 'Kashmiri', native: 'कॉशुर', cn: '克什米尔语', deepL: 0 },
  { code: 'ka', name: 'Georgian', native: 'ქართული', cn: '格鲁吉亚语', deepL: 0 },
  { code: 'kr', name: 'Kanuri', native: 'Kanuri', cn: '卡努里语', deepL: 0 },
  { code: 'kk', name: 'Kazakh', native: 'қазақ тілі', cn: '哈萨克语', deepL: 0 },
  { code: 'km', name: 'Central Khmer', native: 'ខ្មែរ', cn: '高棉语', deepL: 0 },
  { code: 'ki', name: 'Kikuyu', native: 'Gĩkũyũ', cn: '基库尤语', deepL: 0 },
  { code: 'rw', name: 'Kinyarwanda', native: 'Ikinyarwanda', cn: '卢旺达语', deepL: 0 },
  { code: 'ky', name: 'Kirghiz', native: 'Кыргызча', cn: '吉尔吉斯语', deepL: 0 },
  { code: 'kv', name: 'Komi', native: 'коми кыв', cn: '科米语', deepL: 0 },
  { code: 'kg', name: 'Kongo', native: 'Kikongo', cn: '刚果语', deepL: 0 },
  { code: 'ko', name: 'Korean', native: '한국어', cn: '韩语', deepL: 1 },
  { code: 'kj', name: 'Kuanyama', native: 'Kuanyama', cn: '宽亚玛语', deepL: 0 },
  { code: 'ku', name: 'Kurdish', native: 'Kurdî', cn: '库尔德语', deepL: 0 },
  { code: 'lo', name: 'Lao', native: 'ພາສາລາວ', cn: '老挝语', deepL: 0 },
  { code: 'la', name: 'Latin', native: 'latine', cn: '拉丁语', deepL: 0 },
  { code: 'lv', name: 'Latvian', native: 'latviešu valoda', cn: '拉脱维亚语', deepL: 1 },
  { code: 'li', name: 'Limburgish', native: 'Limburgs', cn: '林堡语', deepL: 0 },
  { code: 'ln', name: 'Lingala', native: 'Lingála', cn: '林加拉语', deepL: 0 },
  { code: 'lt', name: 'Lithuanian', native: 'lietuvių kalba', cn: '立陶宛语', deepL: 1 },
  { code: 'lb', name: 'Luxembourgish', native: 'Lëtzebuergesch', cn: '卢森堡语', deepL: 0 },
  { code: 'lu', name: 'Luba-Katanga', native: 'Kiluba', cn: '卢巴-加丹加语', deepL: 0 },
  { code: 'lg', name: 'Ganda', native: 'Luganda', cn: '干达语', deepL: 0 },
  { code: 'mk', name: 'Macedonian', native: 'македонски јазик', cn: '马其顿语', deepL: 0 },
  { code: 'mh', name: 'Marshallese', native: 'Kajin M̧ajeļ', cn: '马绍尔语', deepL: 0 },
  { code: 'mi', name: 'Maori', native: 'te reo Māori', cn: '毛利语', deepL: 0 },
  { code: 'mr', name: 'Marathi', native: 'मराठी', cn: '马拉地语', deepL: 0 },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', cn: '马拉雅拉姆语', deepL: 0 },
  { code: 'mt', name: 'Maltese', native: 'Malti', cn: '马耳他语', deepL: 0 },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu', cn: '马来语', deepL: 0 },
  { code: 'mg', name: 'Malagasy', native: 'fiteny malagasy', cn: '马达加斯加语', deepL: 0 },
  { code: 'mn', name: 'Mongolian', native: 'монгол', cn: '蒙古语', deepL: 0 },
  { code: 'my', name: 'Burmese', native: 'ဗမာစာ', cn: '缅甸语', deepL: 0 },
  { code: 'na', name: 'Nauru', native: 'Dorerin Naoero', cn: '瑙鲁语', deepL: 0 },
  { code: 'nv', name: 'Navajo', native: 'Diné bizaad', cn: '纳瓦霍语', deepL: 0 },
  { code: 'nd', name: 'North Ndebele', native: 'isiNdebele', cn: '北恩德贝莱语', deepL: 0 },
  { code: 'nr', name: 'South Ndebele', native: 'isiNdebele', cn: '南恩德贝莱语', deepL: 0 },
  { code: 'ng', name: 'Ndonga', native: 'Owambo', cn: '恩东加语', deepL: 0 },
  { code: 'ne', name: 'Nepali', native: 'नेपाली', cn: '尼泊尔语', deepL: 0 },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', cn: '荷兰语', deepL: 1 },
  { code: 'nn', name: 'Norwegian Nynorsk', native: 'nynorsk', cn: '新挪威语', deepL: 1 },
  { code: 'nb', name: 'Norwegian Bokmål', native: 'norsk bokmål', cn: '挪威语', deepL: 1 },
  { code: 'no', name: 'Norwegian', native: 'Norsk', cn: '挪威语', deepL: 0 },
  { code: 'ny', name: 'Chichewa', native: 'chiCheŵa', cn: '奇契瓦语', deepL: 0 },
  { code: 'oc', name: 'Occitan', native: 'occitan', cn: '奥克语', deepL: 0 },
  { code: 'oj', name: 'Ojibwa', native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ', cn: '奥吉布瓦语', deepL: 0 },
  { code: 'or', name: 'Oriya', native: 'ଓଡ଼ିଆ', cn: '奥里亚语', deepL: 0 },
  { code: 'om', name: 'Oromo', native: 'Afaan Oromoo', cn: '奥罗莫语', deepL: 0 },
  { code: 'os', name: 'Ossetian', native: 'ирон æвзаг', cn: '奥塞梯语', deepL: 0 },
  { code: 'pa', name: 'Panjabi', native: 'ਪੰਜਾਬੀ', cn: '旁遮普语', deepL: 0 },
  { code: 'pi', name: 'Pali', native: 'पाऴि', cn: '巴利语', deepL: 0 },
  { code: 'pl', name: 'Polish', native: 'polski', cn: '波兰语', deepL: 1 },
  { code: 'pt', name: 'Portuguese', native: 'Português', cn: '葡萄牙语', deepL: 1 },
  { code: 'ps', name: 'Pashto', native: 'پښتو', cn: '普什图语', deepL: 0 },
  { code: 'qu', name: 'Quechua', native: 'Runa Simi', cn: '克丘亚语', deepL: 0 },
  { code: 'rm', name: 'Romansh', native: 'rumantsch grischun', cn: '罗曼什语', deepL: 0 },
  { code: 'ro', name: 'Romanian', native: 'Română', cn: '罗马尼亚语', deepL: 1 },
  { code: 'rn', name: 'Rundi', native: 'Ikirundi', cn: '隆迪语', deepL: 0 },
  { code: 'ru', name: 'Russian', native: 'русский', cn: '俄语', deepL: 1 },
  { code: 'sg', name: 'Sango', native: 'yângâ tî sängö', cn: '桑戈语', deepL: 0 },
  { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्', cn: '梵语', deepL: 0 },
  { code: 'si', name: 'Sinhala', native: 'සිංහල', cn: '僧伽罗语', deepL: 0 },
  { code: 'sk', name: 'Slovak', native: 'slovenčina', cn: '斯洛伐克语', deepL: 1 },
  { code: 'sl', name: 'Slovenian', native: 'slovenščina', cn: '斯洛文尼亚语', deepL: 1 },
  { code: 'se', name: 'Northern Sami', native: 'davvisámegiella', cn: '北萨米语', deepL: 0 },
  { code: 'sm', name: 'Samoan', native: 'gagana fa\'a Samoa', cn: '萨摩亚语', deepL: 0 },
  { code: 'sn', name: 'Shona', native: 'chiShona', cn: '绍纳语', deepL: 0 },
  { code: 'sd', name: 'Sindhi', native: 'سنڌي', cn: '信德语', deepL: 0 },
  { code: 'so', name: 'Somali', native: 'Soomaaliga', cn: '索马里语', deepL: 0 },
  { code: 'st', name: 'Southern Sotho', native: 'Sesotho', cn: '南索托语', deepL: 0 },
  { code: 'es', name: 'Spanish', native: 'Español', cn: '西班牙语', deepL: 1 },
  { code: 'sq', name: 'Albanian', native: 'Shqip', cn: '阿尔巴尼亚语', deepL: 0 },
  { code: 'sc', name: 'Sardinian', native: 'sardu', cn: '撒丁语', deepL: 0 },
  { code: 'sr', name: 'Serbian', native: 'српски језик', cn: '塞尔维亚语', deepL: 0 },
  { code: 'ss', name: 'Swati', native: 'SiSwati', cn: '斯瓦蒂语', deepL: 0 },
  { code: 'su', name: 'Sundanese', native: 'Basa Sunda', cn: '巽他语', deepL: 0 },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili', cn: '斯瓦希里语', deepL: 0 },
  { code: 'sv', name: 'Swedish', native: 'Svenska', cn: '瑞典语', deepL: 1 },
  { code: 'ty', name: 'Tahitian', native: 'Reo Tahiti', cn: '塔希提语', deepL: 0 },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', cn: '泰米尔语', deepL: 0 },
  { code: 'tt', name: 'Tatar', native: 'татар теле', cn: '鞑靼语', deepL: 0 },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', cn: '泰卢固语', deepL: 0 },
  { code: 'tg', name: 'Tajik', native: 'тоҷикӣ', cn: '塔吉克语', deepL: 0 },
  { code: 'tl', name: 'Tagalog', native: 'Wikang Tagalog', cn: '他加禄语', deepL: 0 },
  { code: 'th', name: 'Thai', native: 'ไทย', cn: '泰语', deepL: 1 },
  { code: 'ti', name: 'Tigrinya', native: 'ትግርኛ', cn: '提格里尼亚语', deepL: 0 },
  { code: 'to', name: 'Tonga', native: 'lea faka-Tonga', cn: '汤加语', deepL: 0 },
  { code: 'tn', name: 'Tswana', native: 'Setswana', cn: '茨瓦纳语', deepL: 0 },
  { code: 'ts', name: 'Tsonga', native: 'Xitsonga', cn: '聪加语', deepL: 0 },
  { code: 'tk', name: 'Turkmen', native: 'Türkmen', cn: '土库曼语', deepL: 0 },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', cn: '土耳其语', deepL: 1 },
  { code: 'tw', name: 'Twi', native: 'Twi', cn: '契维语', deepL: 0 },
  { code: 'ug', name: 'Uyghur', native: 'ئۇيغۇرچە', cn: '维吾尔语', deepL: 0 },
  { code: 'uk', name: 'Ukrainian', native: 'Українська', cn: '乌克兰语', deepL: 1 },
  { code: 'ur', name: 'Urdu', native: 'اردو', cn: '乌尔都语', deepL: 0 },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbek', cn: '乌兹别克语', deepL: 0 },
  { code: 've', name: 'Venda', native: 'Tshivenḓa', cn: '文达语', deepL: 0 },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', cn: '越南语', deepL: 1 },
  { code: 'vo', name: 'Volapük', native: 'Volapük', cn: '沃拉普克语', deepL: 0 },
  { code: 'wa', name: 'Walloon', native: 'walon', cn: '瓦隆语', deepL: 0 },
  { code: 'wo', name: 'Wolof', native: 'Wollof', cn: '沃洛夫语', deepL: 0 },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa', cn: '科萨语', deepL: 0 },
  { code: 'yi', name: 'Yiddish', native: 'ייִדיש', cn: '意第绪语', deepL: 0 },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá', cn: '约鲁巴语', deepL: 0 },
  { code: 'za', name: 'Zhuang', native: 'Saɯ cueŋƅ', cn: '壮语', deepL: 0 },
  { code: 'zh', name: 'Chinese (Simplified)', native: '中文（简体）', cn: '中文简体', deepL: 1 },
  { code: 'zu', name: 'Zulu', native: 'isiZulu', cn: '祖鲁语', deepL: 0 },
  { code: 'zh-TW', name: 'Chinese (Traditional)', native: '中文（繁體）', cn: '中文繁体', deepL: 0 },
  { code: 'yue', name: 'Cantonese', native: '廣東話', cn: '粤语', deepL: 0 },
  { code: 'ckb', name: 'Kurdish (Sorani)', native: 'کوردیی ناوەندی', cn: '中库尔德语', deepL: 0 },
  { code: 'pap', name: 'Papiamento', native: 'Papiamentu', cn: '帕皮阿门托语', deepL: 0 },
  { code: 'haw', name: 'Hawaiian', native: 'ʻŌlelo Hawaiʻi', cn: '夏威夷语', deepL: 0 },
  { code: 'fil', name: 'Filipino', native: 'Filipino', cn: '菲律宾语', deepL: 0 },
  { code: 'ceb', name: 'Cebuano', native: 'Cebuano', cn: '宿务语', deepL: 0 },
  { code: 'ilo', name: 'Iloko', native: 'Ilokano', cn: '伊洛卡诺语', deepL: 0 },
  { code: 'war', name: 'Waray', native: 'Winaray', cn: '瓦瑞语', deepL: 0 },
  { code: 'pam', name: 'Kapampangan', native: 'Kapampangan', cn: '邦板牙语', deepL: 0 },
  { code: 'mni', name: 'Manipuri', native: 'মৈতৈলোন্', cn: '曼尼普尔语', deepL: 0 },
  { code: 'lus', name: 'Mizo', native: 'Mizo ṭawng', cn: '米佐语', deepL: 0 },
  { code: 'mzn', name: 'Mazanderani', native: 'مازِرونی', cn: '马赞德兰语', deepL: 0 },
  { code: 'tly', name: 'Talysh', native: 'толышә зывон', cn: '塔利什语', deepL: 0 },
  { code: 'kmr', name: 'Kurdish (Kurmanji)', native: 'Kurmancî', cn: '北库尔德语', deepL: 0 },
  { code: 'ary', name: 'Arabic (Moroccan)', native: 'الدارجة', cn: '摩洛哥阿拉伯语', deepL: 0 },
  { code: 'arz', name: 'Arabic (Egyptian)', native: 'مصرى', cn: '埃及阿拉伯语', deepL: 0 },
  { code: 'azb', name: 'Azerbaijani (South)', native: 'تۆرکجه', cn: '南阿塞拜疆语', deepL: 0 },
  { code: 'map-bms', name: 'Banyumasan', native: 'Basa Banyumasan', cn: '班尤马山语', deepL: 0 },
  { code: 'xmf', name: 'Mingrelian', native: 'მარგალური', cn: '明格列尔语', deepL: 0 },
  { code: 'tet', name: 'Tetum', native: 'Tetun', cn: '德顿语', deepL: 0 },
  { code: 'bar', name: 'Bavarian', native: 'Boarisch', cn: '巴伐利亚语', deepL: 0 },
  { code: 'diq', name: 'Zazaki', native: 'Zazaki', cn: '扎扎其语', deepL: 0 },
  { code: 'zh-min-nan', name: 'Min Nan', native: 'Bân-lâm-gú', cn: '闽南语', deepL: 0 },
  { code: 'gan', name: 'Gan', native: '贛語', cn: '赣语', deepL: 0 },
  { code: 'hak', name: 'Hakka', native: '客家話', cn: '客家话', deepL: 0 },
  { code: 'wuu', name: 'Wu', native: '吳語', cn: '吴语', deepL: 0 },
  { code: 'cdo', name: 'Min Dong', native: 'Mìng-dĕ̤ng', cn: '闽东语', deepL: 0 },
  { code: 'lrc', name: 'Luri', native: 'لوری', cn: '卢尔语', deepL: 0 },
  { code: 'rue', name: 'Rusyn', native: 'русиньскый', cn: '鲁辛语', deepL: 0 },
  { code: 'pms', name: 'Piedmontese', native: 'Piemontèis', cn: '皮埃蒙特语', deepL: 0 },
  { code: 'mai', name: 'Maithili', native: 'मैथिली', cn: '迈蒂利语', deepL: 0 },
  { code: 'new', name: 'Newari', native: 'नेपाल भाषा', cn: '尼瓦尔语', deepL: 0 },
  { code: 'sco', name: 'Scots', native: 'Scots', cn: '苏格兰语', deepL: 0 },
  { code: 'fiu-vro', name: 'Võro', native: 'võro kiil', cn: '维鲁语', deepL: 0 },
  { code: 'vec', name: 'Venetian', native: 'vèneto', cn: '威尼斯语', deepL: 0 },
  { code: 'szl', name: 'Silesian', native: 'ślōnskŏ gŏdka', cn: '西里西亚语', deepL: 0 },
  { code: 'crh', name: 'Crimean Tatar', native: 'qırımtatar tili', cn: '克里米亚鞑靼语', deepL: 0 },
  { code: 'liv', name: 'Livonian', native: 'līvõ kēļ', cn: '利沃尼亚语', deepL: 0 },
  { code: 'ltg', name: 'Latgalian', native: 'latgalīšu volūda', cn: '拉特加莱语', deepL: 0 },
  { code: 'bxr', name: 'Buryat', native: 'буряад хэлэн', cn: '布里亚特语', deepL: 0 },
  { code: 'myv', name: 'Erzya', native: 'эрзянь кель', cn: '埃尔齐亚语', deepL: 0 },
  { code: 'mdf', name: 'Moksha', native: 'мокшень кяль', cn: '莫克沙语', deepL: 0 },
  { code: 'olo', name: 'Livvi-Karelian', native: 'livvin kieli', cn: '利维卡累利阿语', deepL: 0 },
  { code: 'udm', name: 'Udmurt', native: 'удмурт кыл', cn: '乌德穆尔特语', deepL: 0 },
  { code: 'sah', name: 'Sakha', native: 'саха тыла', cn: '雅库特语', deepL: 0 },
  { code: 'koi', name: 'Komi-Permyak', native: 'коми-пермяцкӧй кыв', cn: '科米-彼尔米亚克语', deepL: 0 },
  { code: 'kbd', name: 'Kabardian', native: 'адыгэбзэ', cn: '卡巴尔达语', deepL: 0 },
  { code: 'lez', name: 'Lezgian', native: 'лезги чӀал', cn: '列兹金语', deepL: 0 },
  { code: 'avk', name: 'Kotava', native: 'Kotava', cn: '科塔瓦语', deepL: 0 },
  { code: 'eml', name: 'Emilian', native: 'emiliân', cn: '艾米利亚语', deepL: 0 },
  { code: 'nrm', name: 'Norman', native: 'Nouormand', cn: '诺曼语', deepL: 0 },
  { code: 'bjn', name: 'Banjar', native: 'Banjar', cn: '班查语', deepL: 0 },
  { code: 'din', name: 'Dinka', native: 'Thuɔŋjäŋ', cn: '丁卡语', deepL: 0 },
  { code: 'tpi', name: 'Tok Pisin', native: 'Tok Pisin', cn: '巴布亚皮钦语', deepL: 0 },
  { code: 'snk', name: 'Soninke', native: 'Sooninkanxanne', cn: '索宁克语', deepL: 0 },
  { code: 'fon', name: 'Fon', native: 'Fɔ̀ngbè', cn: '丰语', deepL: 0 },
  { code: 'twq', name: 'Tasawaq', native: 'Tasawaq', cn: '塔萨瓦克语', deepL: 0 },
  { code: 'dzg', name: 'Dazaga', native: 'Dazaga', cn: '达扎加语', deepL: 0 },
  { code: 'mey', name: 'Hassaniya', native: 'حسانية', cn: '哈桑尼亚语', deepL: 0 },
  { code: 'gyr', name: 'Guarayu', native: 'Guarayu', cn: '瓜拉尤语', deepL: 0 },
  { code: 'nhe', name: 'Huastec', native: 'Téenek', cn: '瓦斯特克语', deepL: 0 },
  { code: 'cak', name: 'Kaqchikel', native: 'Kaqchikel', cn: '卡克奇克尔语', deepL: 0 },
  { code: 'quc', name: 'K\'iche\'', native: 'K\'iche\'', cn: '基切语', deepL: 0 },
  { code: 'mam', name: 'Mam', native: 'Qyool', cn: '马姆语', deepL: 0 },
  { code: 'tzj', name: 'Tz\'utujil', native: 'Tz\'utujil', cn: '祖图吉尔语', deepL: 0 },
  { code: 'zat', name: 'Zapotec', native: 'Diidxazá', cn: '萨波特克语', deepL: 0 },
  { code: 'maz', name: 'Mazahua', native: 'Jñatjo', cn: '马萨瓦语', deepL: 0 },
  { code: 'nci', name: 'Nahuatl', native: 'Nāhuatl', cn: '纳瓦特尔语', deepL: 0 },
  { code: 'arn', name: 'Mapudungun', native: 'Mapudungun', cn: '马普切语', deepL: 0 },
  { code: 'quy', name: 'Quechua (Ayacucho)', native: 'Runasimi', cn: '阿亚库乔克丘亚语', deepL: 0 },
  { code: 'guc', name: 'Wayuu', native: 'Wayuunaiki', cn: '瓦尤语', deepL: 0 },
  { code: 'hch', name: 'Huichol', native: 'Wixárika', cn: '维乔尔语', deepL: 0 },
  { code: 'oto', name: 'Otomi', native: 'Hñähñu', cn: '奥托米语', deepL: 0 },
  { code: 'tah', name: 'Tahitian', native: 'Reo Tahiti', cn: '塔希提语', deepL: 0 },
  { code: 'rap', name: 'Rapanui', native: 'Vananga Rapa Nui', cn: '拉帕努伊语', deepL: 0 },
  { code: 'gil', name: 'Gilbertese', native: 'taetae ni Kiribati', cn: '基里巴斯语', deepL: 0 },
  { code: 'pon', name: 'Pohnpeian', native: 'Kitteh', cn: '波纳佩语', deepL: 0 },
  { code: 'kos', name: 'Kosraean', native: 'Kosrae', cn: '科斯拉伊语', deepL: 0 },
  { code: 'chk', name: 'Chuukese', native: 'Chuuk', cn: '丘克语', deepL: 0 },
  { code: 'mik', name: 'Mikasuki', native: 'Mikasuki', cn: '米卡苏基语', deepL: 0 },
  { code: 'cre', name: 'Cree', native: 'Nēhiyawēwin', cn: '克里语', deepL: 0 },
  { code: 'chr', name: 'Cherokee', native: 'ᏣᎳᎩ', cn: '切罗基语', deepL: 0 },
  { code: 'iku', name: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ', cn: '因纽特语', deepL: 0 },
  { code: 'gsw', name: 'Swiss German', native: 'Schwyzerdütsch', cn: '瑞士德语', deepL: 0 },
  { code: 'ksh', name: 'Kölsch', native: 'Kölsch', cn: '科隆语', deepL: 0 },
  { code: 'frr', name: 'North Frisian', native: 'Nordfrasch', cn: '北弗里西亚语', deepL: 0 },
  { code: 'stq', name: 'Saterland Frisian', native: 'Seeltersk', cn: '萨特兰弗里西亚语', deepL: 0 },
  { code: 'nds', name: 'Low German', native: 'Plattdüütsch', cn: '低地德语', deepL: 0 },
  { code: 'pdc', name: 'Pennsylvania German', native: 'Deitsch', cn: '宾夕法尼亚德语', deepL: 0 },
  { code: 'als', name: 'Alemannic', native: 'Alemannisch', cn: '阿勒曼尼语', deepL: 0 },
  { code: 'lad', name: 'Ladino', native: 'Ladino', cn: '拉迪诺语', deepL: 0 },
  { code: 'nov', name: 'Novial', native: 'Novial', cn: '诺维亚语', deepL: 0 },
  { code: 'lfn', name: 'Lingua Franca Nova', native: 'Lingua Franca Nova', cn: '新通用语', deepL: 0 },
  { code: 'jbo', name: 'Lojban', native: 'la .lojban.', cn: '逻辑语', deepL: 0 },
  { code: 'tlh', name: 'Klingon', native: 'tlhIngan Hol', cn: '克林贡语', deepL: 0 },
  { code: 'art', name: 'Artificial', native: 'Artificial', cn: '人工语言', deepL: 0 },
  { code: 'zbl', name: 'Blissymbols', native: 'Blissymbols', cn: '布利斯符号', deepL: 0 },
];

export const LANG_OPTIONS = LANGUAGES.map(l => ({ label: `${l.cn || l.name} (${l.name})`, value: l.code, deepL: l.deepL }));
export const LANG_OPTIONS_WITH_AUTO = [{ label: '自动检测', value: 'auto' }, ...LANG_OPTIONS];
